version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=duofinders
      - POSTGRES_PASSWORD=duofinders
      - POSTGRES_DB=duofinders
    volumes:
      - duofinders_pg_data:/bitnami/postgresql

volumes:
  duofinders_pg_data:
